"""Report Generator — outputs scan results as JSON, Markdown, HTML."""

import json
from html import escape as html_escape
from datetime import datetime
from pathlib import Path
from typing import Optional

from agentsec.attacks.base import AttackResult


class ReportGenerator:
    """Generate scan reports in multiple formats."""

    SEVERITY_COLORS = {
        "critical": "#dc2626",
        "high": "#ea580c",
        "medium": "#ca8a04",
        "low": "#6b7280",
    }

    def generate(self, results: list[AttackResult], target: str) -> dict:
        """Generate structured report data."""
        total = len(results)
        passed = sum(1 for r in results if not r.exploited)
        failed = sum(1 for r in results if r.exploited)
        by_severity = {}
        for r in results:
            if r.exploited:
                by_severity[r.severity] = by_severity.get(r.severity, 0) + 1

        return {
            "target": target,
            "timestamp": datetime.now().isoformat(),
            "summary": {
                "total": total,
                "passed": passed,
                "vulnerable": failed,
                "by_severity": by_severity,
            },
            "findings": [
                {
                    "id": f"{r.name.upper()}-{i:03d}",
                    "name": r.name,
                    "severity": r.severity,
                    "status": "vulnerable" if r.exploited else "passed",
                    "description": r.description,
                    "prompt": r.prompt[:200] if r.prompt else "",
                    "risk": r.risk,
                    "remediation": r.remediation,
                    "tool_calls_involved": len(r.tool_calls),
                }
                for i, r in enumerate(results)
            ],
        }

    def to_json(self, results: list[AttackResult], target: str) -> str:
        """Generate JSON report."""
        return json.dumps(self.generate(results, target), indent=2, ensure_ascii=False)

    def to_markdown(self, results: list[AttackResult], target: str) -> str:
        """Generate Markdown report."""
        data = self.generate(results, target)
        lines = []

        lines.append(f"# Agent Security Scan Report\n")
        lines.append(f"**Target:** `{target}`  ")
        lines.append(f"**Time:** {data['timestamp']}  ")
        lines.append(f"**Tests:** {data['summary']['total']}  \n")

        # Summary badge
        vuln = data['summary']['vulnerable']
        if vuln == 0:
            lines.append("## ✅ 结果: 全部通过\n")
        else:
            lines.append(f"## 🔴 结果: 发现 {vuln} 个漏洞\n")

        lines.append(f"| 严重等级 | 数量 |")
        lines.append(f"|---------|:---:|")
        for sev in ["critical", "high", "medium", "low"]:
            count = data['summary']['by_severity'].get(sev, 0)
            emoji = {"critical": "🔴", "high": "🟠", "medium": "🟡", "low": "⚪"}[sev]
            label = {"critical": "严重", "high": "高危", "medium": "中危", "low": "低危"}[sev]
            lines.append(f"| {emoji} **{label}** | {count} |")
        lines.append("")

        # Pass/fail bar
        pct = data['summary']['passed']
        bar_len = 30
        passed_bar = "🟩" * int(bar_len * pct / max(data['summary']['total'], 1))
        failed_bar = "🟥" * (bar_len - len(passed_bar))
        lines.append(f"```\n[{passed_bar}{failed_bar}] {pct}/{data['summary']['total']} 通过\n```\n")

        # Detailed findings
        lines.append("## 发现详情\n")
        for f in data['findings']:
            status_emoji = "🔴" if f['status'] == 'vulnerable' else "✅"
            lines.append(f"### {status_emoji} {f['id']}: {f['name']}")
            lines.append(f"**严重等级:** {f['severity']}  ")
            lines.append(f"**状态:** {'漏洞' if f['status'] == 'vulnerable' else '通过'}  ")
            lines.append("")
            if f['description']:
                lines.append(f"**描述:** {f['description']}  ")
                lines.append("")
            if f['risk']:
                lines.append(f"**风险:** {f['risk']}  ")
                lines.append("")
            if f['remediation']:
                lines.append(f"**修复建议:**  ")
                for line in f['remediation'].split('\n'):
                    if line.strip():
                        lines.append(f"  - {line.strip()}")
                lines.append("")
            if f['prompt']:
                lines.append(f"**攻击 Payload:** `{f['prompt']}`  ")
                lines.append("")
            lines.append("---\n")

        lines.append("\n*Generated by Agent Security Scanner (agentsec)*")
        return "\n".join(lines)

    def to_html(self, results: list[AttackResult], target: str) -> str:
        """Generate HTML report."""
        target_html = html_escape(target)
        target = target_html

        html = f"""<!DOCTYPE html>
<html lang="zh-CN">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Agent Security Scan Report — {target[:40]}</title>
<style>
  body {{ font-family: -apple-system, BlinkMacSystemFont, sans-serif; max-width: 900px; margin: 40px auto; padding: 0 20px; line-height: 1.6; color: #1a1a2e; background: #f8f9fa; }}
  h1 {{ color: #1a1a2e; border-bottom: 3px solid #4361ee; padding-bottom: 10px; }}
  h2 {{ color: #4361ee; margin-top: 30px; }}
  h3 {{ color: #333; }}
  table {{ border-collapse: collapse; width: 100%; margin: 15px 0; }}
  th, td {{ text-align: left; padding: 10px; border-bottom: 1px solid #ddd; }}
  th {{ background: #4361ee; color: white; }}
  .severity-critical {{ color: #dc2626; font-weight: bold; }}
  .severity-high {{ color: #ea580c; font-weight: bold; }}
  .severity-medium {{ color: #ca8a04; }}
  .severity-low {{ color: #6b7280; }}
  .status-vulnerable {{ color: #dc2626; font-weight: bold; }}
  .status-passed {{ color: #16a34a; }}
  .finding {{ background: white; border-radius: 8px; padding: 20px; margin: 15px 0; box-shadow: 0 2px 4px rgba(0,0,0,0.1); }}
  .finding h3 {{ margin-top: 0; }}
  .badge {{ display: inline-block; padding: 3px 8px; border-radius: 4px; color: white; font-size: 12px; font-weight: bold; }}
  .badge.critical {{ background: #dc2626; }}
  .badge.high {{ background: #ea580c; }}
  .badge.medium {{ background: #ca8a04; }}
  .badge.low {{ background: #6b7280; }}
  code {{ background: #e8e8e8; padding: 2px 6px; border-radius: 3px; font-size: 13px; }}
  .summary-box {{ background: white; border-radius: 8px; padding: 20px; box-shadow: 0 2px 4px rgba(0,0,0,0.1); }}
  .summary-number {{ font-size: 36px; font-weight: bold; }}
  .vuln-bar {{ display: flex; height: 24px; border-radius: 12px; overflow: hidden; margin: 10px 0; }}
  .vuln-seg {{ display: flex; align-items: center; justify-content: center; color: white; font-size: 11px; font-weight: bold; }}
</style>
</head>
<body>
"""
        html += f"<h1>🧪 Agent Security Scan Report</h1>"
        html += f"<p><strong>Target:</strong> <code>{target}</code><br><strong>Time:</strong> {datetime.now().isoformat()}</p>"

        s = self.generate(results, target)['summary']
        html += f"""<div class="summary-box">
  <div style="display: flex; gap: 30px; flex-wrap: wrap;">
    <div><div class="summary-number" style="color:#4361ee;">{s['total']}</div><div>测试总数</div></div>
    <div><div class="summary-number" style="color:#16a34a;">{s['passed']}</div><div>通过</div></div>
    <div><div class="summary-number" style="color:#dc2626;">{s['vulnerable']}</div><div>漏洞</div></div>
  </div>
"""
        if s['by_severity']:
            html += '<table><tr><th>等级</th><th>数量</th></tr>'
            for sev in ['critical', 'high', 'medium', 'low']:
                c = s['by_severity'].get(sev, 0)
                if c:
                    labels = {'critical': '严重', 'high': '高危', 'medium': '中危', 'low': '低危'}
                    html += f'<tr><td class="severity-{sev}">{labels[sev]}</td><td>{c}</td></tr>'
            html += '</table>'
        html += '</div>'

        html += '<h2>发现详情</h2>'
        for f in self.generate(results, target)['findings']:
            sev = html_escape(f['severity'])
            status = html_escape(f['status'])
            f = {
                key: html_escape(value) if isinstance(value, str) else value
                for key, value in f.items()
            }
            html += f"""<div class="finding">
  <h3>{'🔴' if status == 'vulnerable' else '✅'} {f['id']}: {f['name']}</h3>
  <p><span class="badge {sev}">{sev.upper()}</span> <span class="status-{status}">{'漏洞' if status == 'vulnerable' else '通过'}</span></p>
"""
            if f['description']:
                html += f"<p><strong>描述:</strong> {f['description']}</p>"
            if f['risk']:
                html += f"<p><strong>风险:</strong> {f['risk']}</p>"
            if f['remediation']:
                html += "<p><strong>修复建议:</strong></p><ul>"
                for line in f['remediation'].split('\n'):
                    if line.strip():
                        html += f"<li>{line.strip()}</li>"
                html += "</ul>"
            if f['prompt']:
                html += f"<p><strong>攻击 Payload:</strong> <code>{f['prompt'][:100]}</code></p>"
            html += "</div>"

        html += f'<p style="color:#999;font-size:12px;margin-top:40px;">Generated by Agent Security Scanner (agentsec)</p>'
        html += "</body></html>"
        return html

    def save(self, results: list[AttackResult], target: str, path: str) -> str:
        """Save report to file, auto-detecting format from extension."""
        fmt = Path(path).suffix.lower()
        if fmt == ".json":
            content = self.to_json(results, target)
        elif fmt == ".html":
            content = self.to_html(results, target)
        else:
            content = self.to_markdown(results, target)
            if not fmt:
                path += ".md"

        Path(path).write_text(content, encoding="utf-8")
        return path
