"""Watch mode — schedule recurring agent security scans via Hermes cron."""

import shlex
import sys
from pathlib import Path

from rich.console import Console
from rich.panel import Panel
from rich.markup import escape

console = Console()
ERR = Console(stderr=True)

WATCH_SCRIPT_TEMPLATE = """#!/bin/bash
# agentsec watch script — auto-generated by `agentsec watch`
# Schedule: {schedule}
# Profile: {profile}
# Target: {target}

set -euo pipefail

echo "=== Agent Security Scan [{datetime}] ==="
echo "Target: {target}  Profile: {profile}"
echo ""

# Run scan
agentsec scan {target} --profile {profile} 2>&1 || true

echo ""
echo "=== Scan complete ==="
"""


def cmd_watch(target: str, schedule: str = "24h", profile: str = "full",
              create: bool = False):
    """Set up recurring security scans via Hermes cron."""

    # ── Resolve schedule ──────────────────────────────────────
    cron_expr = _resolve_schedule(schedule)
    schedule_label = _format_schedule(schedule)

    console.print(Panel(f"[bold]⏰ Agent Security Watch[/bold]\n"
                        f"[dim]Target: {escape(target)}[/dim]\n"
                        f"[dim]Schedule: {schedule_label} ({cron_expr})[/dim]\n"
                        f"[dim]Profile: {profile}[/dim]"))

    # ── Create watch script ───────────────────────────────────
    scripts_dir = Path.home() / ".hermes" / "scripts"
    scripts_dir.mkdir(parents=True, exist_ok=True)

    script_path = scripts_dir / "agentsec-watch.sh"
    script_content = WATCH_SCRIPT_TEMPLATE.format(
        schedule=schedule_label,
        profile=profile,
        target=target,
        datetime="$(date '+%Y-%m-%d %H:%M')",
    )
    script_path.write_text(script_content)
    script_path.chmod(0o755)

    console.print(f"\n[green]✅ Watch script created:[/green] {script_path}")
    console.print()

    # ── Show cron setup instructions ──────────────────────────
    console.print("[bold]To activate watch, tell your Hermes agent:[/bold]")
    console.print()
    console.print(f"  [dim]# Replace YOUR_SCHEDULE with your preferred cron expression[/dim]")
    console.print(f"  [bold cyan]Schedule a cron job to run agentsec-watch.sh[/bold cyan]")
    console.print(f"  [bold cyan]every {schedule} and deliver results to me[/bold cyan]")
    console.print()
    console.print("[dim]Or use these exact cron expressions:[/dim]")
    console.print(f"  [cyan]Every 12h:[/cyan]   0 */12 * * *")
    console.print(f"  [cyan]Every 24h:[/cyan]   0 6 * * *")
    console.print(f"  [cyan]Weekly:[/cyan]     0 6 * * 1")
    console.print(f"  [cyan]Custom:[/cyan]     {cron_expr}")
    console.print()

    # ── Show what the script does ─────────────────────────────
    console.print("[bold]What will happen:[/bold]")
    console.print(f"  • Runs [cyan]agentsec scan {target} --profile {profile}[/cyan]")
    console.print(f"  • Delivers the scan report to you automatically")
    console.print(f"  • Results appear in your chat at the scheduled time")
    console.print()

    # ── Manual cron command for direct use ────────────────────
    console.print("[bold]Or run this command directly (from another terminal):[/bold]")
    console.print()
    console.print(f"  [dim]# Using crontab directly:[/dim]")
    console.print(f"  [green](crontab -l 2>/dev/null; echo \"{cron_expr} {script_path}\") | crontab -[/green]")
    console.print()
    console.print("[dim]Note: crontab requires the hermes venv to be activated in the script.[/dim]")
    console.print("[dim]The Hermes cron scheduler handles this automatically.[/dim]")

    return 0


def _resolve_schedule(schedule: str) -> str:
    """Convert human-friendly schedule to cron expression."""
    schedule_map = {
        "1h": "0 * * * *",
        "2h": "0 */2 * * *",
        "6h": "0 */6 * * *",
        "12h": "0 */12 * * *",
        "24h": "0 6 * * *",
        "daily": "0 6 * * *",
        "weekly": "0 6 * * 1",
        "weekday": "0 6 * * 1-5",
    }
    if schedule in schedule_map:
        return schedule_map[schedule]
    # Try to parse as cron expression directly
    parts = schedule.strip().split()
    if len(parts) == 5:
        return schedule
    # Default to 24h
    return "0 6 * * *"


def _format_schedule(schedule: str) -> str:
    """Format schedule for display."""
    labels = {
        "1h": "every 1 hour",
        "2h": "every 2 hours",
        "6h": "every 6 hours",
        "12h": "every 12 hours",
        "24h": "every 24 hours (06:00 UTC)",
        "daily": "daily (06:00 UTC)",
        "weekly": "weekly (Monday 06:00 UTC)",
        "weekday": "weekdays (06:00 UTC)",
    }
    if schedule in labels:
        return labels[schedule]
    return f"cron: {schedule}"
